import { useState } from 'react'
import { BarChart, LineChart, DonutChart } from './Charts'
import { categories, PLACES, matching, nearMisses, alertRecipients, metrics, visibleListings, visibleTransactions, weeksFor, dateLabel, uid, impactFor } from './portfolio'
import { money } from './engine'
const STATUS=['Live','Needs review','On hold','In trade','Completed']
const labelCat=k=>categories[k]?.label||k
export function AlertChoice({listing,portfolio,onChoice}){
  const recipients=alertRecipients(listing,portfolio),choice=listing.alertChoice
  return <div className="alert-choice">
    <h3>No match yet. Would you like to alert nearby buyers?</h3>
    <p className="muted">Your listing stays live either way. {recipients.length} potential {recipients.length===1?'buyer':'buyers'} within 50 km follow this category.</p>
    {!choice && <div className="row"><button className="accept-button" disabled={!recipients.length} onClick={()=>onChoice('send')}>Yes, send buyer alerts</button><button className="match-button" onClick={()=>onChoice('decline')}>Not now</button></div>}
    {choice==='declined'&&<><p className="muted">No alerts sent. You can send them later.</p><button className="match-button" disabled={!recipients.length} onClick={()=>onChoice('send')}>Send alerts now</button></>}
    {choice==='sent'&&<p className="tag green">✓ Seller-approved alerts simulated for {recipients.length} potential buyers</p>}
    {choice==='none'&&<p className="muted">No nearby recipients are available yet. No alerts were sent.</p>}
    {!!recipients.length&&<details><summary>{choice==='sent'?'Alert recipients':'Preview potential recipients'}</summary>{recipients.map(r=><div className="notice" key={r.id}><strong>{r.name}</strong><small> · {r.km} km · {r.type}</small><p>{listing.quantity} {listing.unit} {listing.material}. Suggested use: {categories[listing.cat].uses[listing.flags?.nofeed&&listing.cat==='plant'?1:0]}. {categories[listing.cat].benefit}</p></div>)}</details>}
    <p className="muted small">Demo only: approval creates an in-app notification record. No email, SMS or external message is sent.</p>
  </div>
}
function Stats({items}){return <div className="hub-stats">{items.map(([label,value])=><div className="hub-card stat" key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>}
function MatchSummary({m,onTrade}){
  const [verified,setVerified]=useState(false)
  return <article className="hub-card"><div className="hub-card-head"><div><h3>{m.supply?.material||'Your material'} → {m.buyer.name}</h3><p className="muted small">{m.d.pathway} · {m.route.km} km · {m.score}% match</p></div><span className={'tag '+(m.verify?'grey':'green')}>{m.verify?'Suitability check':'Ready to review'}</span></div><div className="figures"><div><small>Goods</small><strong>{money(m.goods)}</strong></div><div><small>Transport hold</small><strong>{money(m.route.cost)}</strong></div><div><small>Disposal avoided (est.)</small><strong>{money(m.sellerSaving)}</strong></div></div><details><summary>Why this match</summary><p className="muted small">Category and quantity fit the request; the route is within {m.d.maxKm} km. Estimated buyer saving: {money(m.buyerSaving)}. Distances, prices and suitability checks are demo scenarios.</p></details>{m.verify&&<label className="check"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/><span>I have reviewed the source/condition and confirmed suitability for the buyer's intended use.</span></label>}<button className="accept-button" disabled={m.verify&&!verified} onClick={()=>onTrade({...m,buyerVerified:verified})}>Review trade and payment</button></article>
}
export function RequestForm({user,onSave,onCancel,initialData}){
  const [f,setF]=useState(()=>initialData||{material:'Plant material',cat:'plant',unit:'kg',min:'100',max:'1000',price:'0.2',marketRate:'0.35',maxKm:'50',location:'Northland',use:'composting',collectDays:'7'})
  const [err,setErr]=useState(''),set=(k,v)=>setF({...f,[k]:v,...(k==='cat'&&v!=='plant'&&f.use==='feed'?{use:'composting'}:{})})
  function submit(e){e.preventDefault();const min=+f.min,max=+f.max,price=+f.price,km=+f.maxKm,days=+f.collectDays;if(!f.material.trim()||![min,max,price,km,days,+f.marketRate].every(Number.isFinite)||min<=0||max<min||price<0||km<=0||days<=0||+f.marketRate<0)return setErr('Enter a material, a valid quantity range, non-negative prices, and positive distance/days.')
    const now=new Date(),until=new Date(now);until.setDate(until.getDate()+days)
    onSave({...f,id:initialData?.id||uid(),owner:user.email,business:user.farm,type:'Demand',quantity:max,min,max,price,marketRate:+f.marketRate,maxKm:km,collectDays:days,from:now.toISOString().slice(0,10),until:until.toISOString().slice(0,10),createdAt:initialData?.createdAt||now.toISOString(),status:'Live',archived:false,flags:{hold:false,nofeed:false,unsure:[]}})
  }
  return <section className="panel"><h2>Request a material</h2><p className="muted">Tell nearby suppliers what your business can reuse.</p><form onSubmit={submit}><div className="form-grid"><label>Material<input value={f.material} onChange={e=>set('material',e.target.value)}/></label><label>Category<select value={f.cat} onChange={e=>set('cat',e.target.value)}>{Object.entries(categories).map(([k,c])=><option key={k} value={k}>{c.label}</option>)}</select></label><label>Unit<select value={f.unit} onChange={e=>set('unit',e.target.value)}>{['kg','m³','bales'].map(u=><option key={u}>{u}</option>)}</select></label>{[['min','Minimum quantity'],['max','Maximum quantity'],['price','Maximum unit price ($)'],['marketRate','Alternative unit cost ($, estimate)'],['maxKm','Maximum route distance (km)'],['collectDays','Needed within (days)']].map(([k,label])=><label key={k}>{label}<input type="number" min="0" step="any" value={f[k]} onChange={e=>set(k,e.target.value)}/></label>)}<label>Location<select value={f.location} onChange={e=>set('location',e.target.value)}>{PLACES.map(p=><option key={p}>{p}</option>)}</select></label><label>Intended use<select value={f.use} onChange={e=>set('use',e.target.value)}>{['composting','worm farming','mulch','craft fibre','material trials',...(f.cat==='plant'?['feed']:[])].map(u=><option key={u}>{u}</option>)}</select></label></div><p className="muted small">A request is not feed-suitability approval. Buyers must verify lawful use and material condition before trading.</p>{err&&<p className="error" role="alert">{err}</p>}<button className="voice-button">Publish buyer request</button><button type="button" className="link" onClick={onCancel}>Cancel</button></form></section>
}
export function Hub({tab,portfolio,user,onGo,onOpen,onTrade,onEdit,onArchive,onDelete,onAlert,onSaveRequest,onOffer,onCancelTrade,onDispute,onResolve,onMarkRead,onSignIn,onWithdrawOffer}){
  const [scope,setScope]=useState('mine'),[q,setQ]=useState(''),[type,setType]=useState('All'),[category,setCategory]=useState('All'),[status,setStatus]=useState('Active'),[limit,setLimit]=useState(12),[selected,setSelected]=useState(''),[showRequest,setShowRequest]=useState(false),[offer,setOffer]=useState(null),[offerPrice,setOfferPrice]=useState(''),[offerMessage,setOfferMessage]=useState('')
  const all=visibleListings(portfolio),txs=visibleTransactions(portfolio),mine=portfolio.listings,mineTx=portfolio.transactions
  const shownScope=scope==='mine'?mine:all,shownTx=scope==='mine'?mineTx:txs,m=metrics(shownScope,shownTx),weeks=weeksFor(shownTx)
  const live=mine.filter(l=>!l.archived&&l.status==='Live'),matchCount=live.reduce((a,l)=>a+matching(l,portfolio).length,0)
  const scopes=<div className="hub-scope" role="group" aria-label="Data scope">{[['mine','My activity'],['demo','Demo marketplace']].map(([v,label])=><button key={v} className={scope===v?'on':''} onClick={()=>setScope(v)}>{label}</button>)}<span className="muted small">{scope==='mine'?'Your records in this browser':'Includes imported fictional businesses and one completed example'}</span></div>
  const mineMatches=selected?live.filter(l=>l.id===selected):live
  if(!user.email)return <div className="hub-card"><h2>{tab}</h2><p className="muted">Log in to view your saved activity and explore the demo marketplace.</p><button className="match-button" onClick={onSignIn}>Log in</button></div>
  if(showRequest)return <RequestForm user={user} initialData={typeof showRequest==='object'?showRequest:null} onSave={r=>{onSaveRequest(r);setShowRequest(false)}} onCancel={()=>setShowRequest(false)}/>
  return <div className="hub-view"><div className="hub-title"><div><p className="eyebrow">YOUR RESOURCE EXCHANGE</p><h2>{tab}</h2><p className="muted">{tab==='Dashboard'?`Kia ora, ${user.farm}. See what needs your attention.`:tab==='Impact'?'Completed reuse, with clear assumptions.':tab==='Marketplace'?'Find useful local materials and buyer requests.':tab==='Matches'?'Review compatible uses, quantities and routes.':'Track agreements, delivery updates and payment outcomes.'}</p></div><button className="accept-button" onClick={()=>onGo('Create Listing')}>+ Create listing</button></div>
    {['Dashboard','Impact'].includes(tab)&&scopes}
    {tab==='Dashboard'&&<>
      <Stats items={[['Active listings & requests',m.active.length],['Open exchanges',m.open.length],['Completed exchanges',m.done.length],['Material reused (kg)',m.kg.toLocaleString('en-NZ')],['Goods exchanged',money(m.value)],['Net CO₂e (kg, estimate)',m.net.toLocaleString('en-NZ')]]}/>
      <div className="hub-card"><h3>Next actions</h3>{!mine.length&&<div className="action-row"><p>Start with a surplus listing or a buyer request.</p><button className="match-button" onClick={()=>onGo('Create Listing')}>List surplus</button><button className="match-button" onClick={()=>setShowRequest(true)}>Request material</button></div>}{mineTx.filter(t=>!['Completed','Cancelled'].includes(t.status)).map(t=><div className="action-row" key={t.id}><div><strong>{t.listing.material} · {t.status}</strong><p className="muted small">{t.status==='Disputed'?'Payment release paused pending review':t.stage===0?'Record pickup after both payments':t.stage===1?'Carrier must confirm delivered quantity':t.stage===2?'Review conditions and release eligible funds':'Confirm payments'} · {t.buyer}</p></div><button className="match-button" onClick={()=>onOpen(t)}>Open exchange</button></div>)}{live.filter(l=>l.type==='Supply'&&!matching(l,portfolio).length&&!l.alertChoice).map(l=><div className="action-row" key={l.id}><div><strong>No match for {l.material}</strong><p className="muted small">Choose whether to notify nearby buyers.</p></div><button className="match-button" onClick={()=>{setSelected(l.id);onGo('Matches')}}>Review alerts</button></div>)}{matchCount>0&&<div className="action-row"><p>{matchCount} candidate matches are ready to review.</p><button className="match-button" onClick={()=>onGo('Matches')}>See matches</button></div>}{mine.length>0&&!matchCount&&!m.open.length&&<p className="muted">No exchanges need action. Your live listings remain available.</p>}</div>
      <div className="charts-grid"><BarChart title="Supply by location" description="Available kg in live supply listings; non-weight units are excluded." unit="kg" data={Object.entries(m.active.filter(l=>l.type==='Supply'&&l.unit==='kg').reduce((a,l)=>({...a,[l.location]:(a[l.location]||0)+l.quantity}),{})).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([label,value])=>({label,value}))}/><LineChart title="Completed reuse by week" description="Eight weeks of confirmed completed transactions. Pending trades are excluded." unit="kg" data={weeks.map(w=>({label:w.label,value:w.kg}))}/><DonutChart title="Listing status mix" description="All supply listings and buyer requests in the selected scope." data={STATUS.map(label=>({label,value:shownScope.filter(l=>!l.archived&&l.status===label).length})).filter(d=>d.value>0)}/></div>
      <div className="hub-card"><h3>Recent activity</h3>{portfolio.notifications.length?portfolio.notifications.slice(0,5).map(n=><div className="action-row" key={n.id}><div><p>{n.text}</p><small className="muted">{dateLabel(n.createdAt)} · {n.read?'Read':'Unread'}</small></div><button className="link" onClick={()=>{onMarkRead(n.id);onGo(n.tab)}}>View</button></div>):<p className="muted">Listing, alert and delivery updates will appear here.</p>}</div>
    </>}
    {tab==='Marketplace'&&<>
      <div className="hub-card filters"><label>Search<input type="search" placeholder="Material, business or location" value={q} onChange={e=>setQ(e.target.value)}/></label><label>Listing type<select value={type} onChange={e=>setType(e.target.value)}>{['All','Supply','Demand','Mine'].map(x=><option key={x}>{x}</option>)}</select></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{Object.entries(categories).map(([k,c])=><option key={k} value={k}>{c.label}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['Active','Archived','All'].map(x=><option key={x}>{x}</option>)}</select></label><button className="match-button" onClick={()=>setShowRequest(true)}>+ Buyer request</button></div>
      {(()=>{const filtered=all.filter(l=>(type==='All'||type==='Mine'&&l.owner===user.email||l.type===type)&&(category==='All'||l.cat===category)&&(status==='All'||status==='Archived'&&l.archived||status==='Active'&&!l.archived)&&`${l.material} ${l.business} ${l.location}`.toLowerCase().includes(q.toLowerCase()));return <><p className="muted small">{filtered.length} listings · fictional examples are labelled</p><div className="listing-grid">{filtered.slice(0,limit).map(l=>{const hasTrade=mineTx.some(t=>t.listingId===l.id&&!['Completed','Cancelled'].includes(t.status));return <article className="hub-card" key={l.id}><div className="hub-card-head"><span className="tag grey">{l.type==='Supply'?'Available':'Wanted'}</span><span className={'tag '+(l.status==='Live'?'green':'grey')}>{l.archived?'Archived':l.status}</span></div><h3>{l.material}</h3><p className="muted small">{l.business} · {l.location}</p><strong className="listing-quantity">{l.type==='Supply'?l.quantity.toLocaleString('en-NZ'):`${l.min}–${l.max}`} {l.unit}</strong><p className="muted small">{labelCat(l.cat)}</p><p>{l.type==='Supply'?'Asking':'Budget up to'} {money(l.price)}/{l.unit}{l.type==='Demand'?` · ${l.maxKm} km range`:''}</p><p className="muted small">{l.condition||l.use} · until {dateLabel(l.until)}</p>{l.sample&&<small className="demo-label">Fictional marketplace example</small>}{l.owner===user.email&&<div className="row"><button className="link" disabled={hasTrade||l.status==='Completed'} onClick={()=>l.type==='Demand'?setShowRequest(l):onEdit(l)}>Edit</button><button className="link" disabled={hasTrade} onClick={()=>onArchive(l.id)}>{l.archived?'Restore':'Archive'}</button><button className="link" disabled={hasTrade} onClick={()=>onDelete(l.id)}>Delete</button></div>}<details><summary>Details &amp; suitability</summary><p className="muted small">{l.flags?.hold?'Movement or safety hold: trade is blocked.':l.status==='Needs review'?'Chemical history or suitability is uncertain. Review needed before trade.':'Use and condition must be reviewed before agreement; this is not a compliance certificate.'}</p>{Object.entries(l.answers||{}).map(([k,v])=><p className="muted small" key={k}>{categories[l.cat].questions.find(x=>x.id===k)?.text} {v}</p>)}</details></article>})}</div>{!filtered.length&&<div className="hub-card"><p>No listings match these filters.</p></div>}{filtered.length>limit&&<button className="match-button" onClick={()=>setLimit(n=>n+12)}>Show more listings</button>}</>})()}
    </>}
    {tab==='Matches'&&<>
      <div className="hub-card filters"><label>Your listing or request<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">All active listings</option>{live.map(l=><option key={l.id} value={l.id}>{l.material} · {l.type}</option>)}</select></label><button className="match-button" onClick={()=>setShowRequest(true)}>Create buyer request</button></div>
      {!mineMatches.length&&<div className="hub-card"><p>No live listings yet. Create a supply listing or buyer request to find matches.</p></div>}
      {mineMatches.map(l=>{const ms=matching(l,portfolio),near=nearMisses(l,portfolio);return <section key={l.id}><div className="section-head"><h3>{l.material}</h3><span className="muted small">{ms.length} candidates · {l.quantity} {l.unit} · {l.location}</span></div>{ms.map(m=><MatchSummary key={m.d.id+(m.supply?.id||'')} m={{...m,supply:m.supply||l}} onTrade={chosen=>onTrade(chosen.supply,chosen)}/>)}{!ms.length&&l.type==='Supply'&&<div className="hub-card"><AlertChoice listing={l} portfolio={portfolio} onChoice={choice=>onAlert(l,choice)}/></div>}{!ms.length&&l.type==='Demand'&&<div className="hub-card"><p className="muted">No supplier fits the category, quantity, budget, dates and distance yet. Your request stays live.</p></div>}{near.length>0&&<div className="hub-card"><h3>Near matches</h3><p className="muted small">These requests fit the route and use, but need a different quantity or price. An offer does not start a trade or bypass checks.</p>{near.map(n=><div className="action-row" key={n.request.id}><div><strong>{n.request.business}</strong><p className="muted small">Needs adjustment: {n.reasons.join(', ')} · budget {money(n.request.price)}/{l.unit}</p></div><button className="match-button" onClick={()=>{setOffer({listing:l,request:n.request});setOfferPrice(String(Math.min(l.price,n.request.price)));setOfferMessage('')}}>Draft offer</button></div>)}</div>}</section>})}
    </>}
    {tab==='Transactions'&&<>
      <p className="muted small">All payments, refunds and offers are simulated. No funds are collected.</p>
      {portfolio.offers.length>0&&<div className="hub-card"><h3>Offers</h3>{portfolio.offers.map(o=><div className="action-row" key={o.id}><div><strong>{o.material} → {o.buyer}</strong><p className="muted small">{money(o.price)} per unit · {o.quantity} · {o.status}</p><p>{o.message}</p></div><div><span className="tag grey">{o.status==='Pending'?'Awaiting demo buyer response':o.status}</span>{o.status==='Pending'&&<button className="link" onClick={()=>onWithdrawOffer(o.id)}>Withdraw offer</button>}</div></div>)}</div>}
      {!mineTx.length&&<div className="hub-card"><p>No transactions yet. Review a match to start an exchange.</p><button className="match-button" onClick={()=>onGo('Matches')}>See matches</button></div>}
      {mineTx.map(t=><article className="hub-card" key={t.id}><div className="hub-card-head"><div><h3>{t.listing.material} → {t.buyer}</h3><p className="muted small">{t.listing.quantity} {t.listing.unit} agreed · {t.km} km · {dateLabel(t.createdAt)}</p></div><span className={'tag '+(t.status==='Completed'?'green':'grey')}>{t.status}</span></div><div className="figures"><div><small>Goods held originally</small><strong>{money(t.listing.quantity*t.listing.price)}</strong></div><div><small>Goods {t.status==='Completed'?'released':'eligible'}</small><strong>{money(t.settlement?.releasedGoods||0)}</strong></div><div><small>Buyer refund {t.status==='Completed'?'paid':'estimate'}</small><strong>{money(t.settlement?.buyerRefund||0)}</strong></div></div><details><summary>Timeline and payment details</summary>{t.log.map((e,i)=><div className="timeline-row" key={i}><small>{dateLabel(e.at)}</small><p>{e.text}</p></div>)}<p className="muted small">Goods fee: {money(t.settlement?.fee||0)} · seller payout: {money(t.settlement?.sellerGets||0)} · seller transport refund: {money(t.settlement?.transport||0)}{t.status==='Cancelled'?` · Full refund: ${money(t.paid.buyer?t.listing.quantity*t.listing.price:0)} buyer goods hold plus ${money(t.settlement?.transport||0)} seller transport hold`:''}</p></details><div className="row">{!['Cancelled'].includes(t.status)&&<button className="match-button" onClick={()=>onOpen(t)}>Open exchange</button>}{!['Completed','Cancelled','Disputed'].includes(t.status)&&<><button className="link" onClick={()=>onDispute(t)}>Raise dispute</button>{t.stage===0&&<button className="link" onClick={()=>onCancelTrade(t)}>Cancel and refund</button>}</>}{t.status==='Disputed'&&<button className="link" onClick={()=>onResolve(t)}>Resolve demo dispute</button>}</div></article>)}
    </>}
    {tab==='Impact'&&<>
      <Stats items={[['Completed exchanges',m.done.length],['Material reused (kg)',m.kg.toLocaleString('en-NZ')],['Net CO₂e (kg, estimate)',m.net.toLocaleString('en-NZ')],['Disposal costs avoided (est.)',money(m.savings)],['Seller goods payouts',money(m.sales)],['Goods exchanged',money(m.value)]]}/>
      <div className="charts-grid"><LineChart title="Net impact by week" description="Completed exchanges only. Negative estimates are shown when transport outweighs the benefit." unit="kg CO₂e" data={weeks.map(w=>({label:w.label,value:w.co2}))}/><BarChart title="Reuse by category" description="Confirmed completed weight, grouped by material category." unit="kg" data={Object.entries(m.done.filter(t=>t.listing.unit==='kg').reduce((a,t)=>({...a,[t.listing.cat]:(a[t.listing.cat]||0)+t.quantity}),{})).map(([k,value])=>({label:labelCat(k),value}))}/></div>
      <div className="hub-card"><h3>Potential impact of live listings</h3><p className="muted">{m.active.filter(l=>l.type==='Supply'&&l.unit==='kg').reduce((a,l)=>a+l.quantity,0).toLocaleString('en-NZ')} kg available for reuse. This is projected availability and is not counted as completed impact.</p></div>
      <div className="hub-card"><h3>Completed exchange estimates</h3>{m.done.length?<div className="table-scroll"><table><thead><tr><th>Material</th><th>Reused</th><th>Net CO₂e</th><th>Scenario range</th></tr></thead><tbody>{m.done.map(t=>{const i=impactFor(t.quantity,t.km,t.listing.unit);return <tr key={t.id}><td>{t.listing.material}{t.sample?' (fictional)':''}</td><td>{i.excluded?`${t.quantity} ${t.listing.unit} (weight unknown)`:`${i.kg} kg`}</td><td>{i.excluded?'Excluded':`${i.co2} kg`}</td><td>{i.excluded?'—':`${i.low}–${i.high} kg`}</td></tr>})}</tbody></table></div>:<p className="muted">Complete an exchange to see its realised reuse scenario.</p>}</div>
      <details className="hub-card"><summary>How the estimates work</summary><p className="muted small">Illustrative factors adapted from the reference demo: avoided disposal 450 kg CO₂e/t; displaced production 60 kg/t with 70% substitution; processing 20 kg/t; truck 0.9 kg/km for one route. Net = quantity × (450 + 60 × 0.7 − 20) − route km × 0.9. Range varies substitution from 0% to 100%, not a statistical confidence interval. Actual accepted delivery weight is used; each completed transaction counts once. Non-weight units are excluded unless weighed. Estimates are not verified carbon reductions or credits. They exclude return travel, full life-cycle effects and funded transport policy costs.</p></details>
    </>}
    {offer&&<div className="modal-back"><div className="modal" role="dialog" aria-modal="true" aria-label="Draft offer"><h3>Offer for {offer.listing.material}</h3><p className="muted">To {offer.request.business}. No external message will be sent.</p><label>Proposed unit price ($)<input type="number" min="0" step="0.01" value={offerPrice} onChange={e=>setOfferPrice(e.target.value)}/></label><label>Message<input value={offerMessage} onChange={e=>setOfferMessage(e.target.value)}/></label><p className="muted small">Quantity proposals can be negotiated with the buyer; the existing quantity is not silently changed.</p><button className="voice-button" disabled={offerPrice===''||!Number.isFinite(+offerPrice)||+offerPrice<0} onClick={()=>{onOffer({id:uid(),listingId:offer.listing.id,requestId:offer.request.id,material:offer.listing.material,buyer:offer.request.business,quantity:offer.listing.quantity,price:+offerPrice,message:offerMessage,status:'Pending',createdAt:new Date().toISOString()});setOffer(null)}}>Save simulated offer</button><button className="link" onClick={()=>setOffer(null)}>Cancel</button></div></div>}
  </div>
}
